# Generated by Django 2.0.6 on 2018-06-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='BuildProject',
        ),
        migrations.RemoveField(
            model_name='change',
            name='merges',
        ),
        migrations.AddField(
            model_name='build',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='harvester.BuildProject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='change',
            name='merges_to',
            field=models.ManyToManyField(related_name='_change_merges_to_+', to='harvester.Change'),
        ),
        migrations.AddField(
            model_name='issue',
            name='change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_issues', to='harvester.Change'),
        ),
        migrations.AlterField(
            model_name='change',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='integrationtype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
