# Generated by Django 2.0.6 on 2018-06-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0002_auto_20180625_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='finished',
            field=models.DateTimeField(blank=True, help_text='Build Finished Timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='started',
            field=models.DateTimeField(blank=True, help_text='Build Started Timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='merges_to',
            field=models.ManyToManyField(blank=True, related_name='_change_merges_to_+', to='harvester.Change'),
        ),
    ]
